- id: fd610730ce0b42a19ba83210eb1b80d4
  alias: Update Available Notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify
    data:
      message: Update for Home Assistant is available.
- id: '1542616274048'
  alias: Mirror Follow
  trigger:
  - entity_id: switch.bathroom_wall
    platform: state
  action:
  - service: script.turn_on
    data:
      entity_id:
      - script.mirror_update
- id: '1543219061236'
  alias: Ambiance Follow
  trigger:
  - entity_id: switch.bathroom_heater
    platform: state
  - entity_id: light.bathroom_mirror_inside_inner
    platform: state
  action:
  - service: script.turn_on
    data:
      entity_id:
      - script.mirror_update_ambiance
- id: '1543219061295'
  alias: Night Light Follow
  trigger:
  - entity_id: switch.bathroom_nightlight
    platform: state
  action:
  - service: script.turn_on
    data:
      entity_id:
      - script.nightlight_update
- id: '1543222884226'
  alias: Update OZW
  trigger:
    platform: time
    at: '4:26:13'
  action:
  - service: zwave.update_config
- id: '1543390183529'
  alias: Utility Closet
  trigger:
  - entity_id: binary_sensor.door_utility_closet
    platform: state
  action:
  - data:
      entity_id: switch.outlet_utility_closet
    service_template: 'switch.turn_{{ ''on'' if is_state(''binary_sensor.door_utility_closet'',
      ''off'') else ''off'' }}

      '
